//! Emits CO-RE field byte offsets from `/sys/kernel/btf/vmlinux` when available.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

const BTF_MAGIC: u16 = 0xEB9F;
const DEFAULT_BTF_PATH: &str = "/sys/kernel/btf/vmlinux";

const TARGETS: [(&str, &str); 5] = [
    ("linux_binprm", "file"),
    ("file", "f_inode"),
    ("inode", "i_ino"),
    ("inode", "i_sb"),
    ("super_block", "s_dev"),
];

const UNVERIFIED_DEVELOPMENT_FALLBACK: [(&str, &str, u32); 5] = [
    ("linux_binprm", "file", 64),
    ("file", "f_inode", 168),
    ("inode", "i_ino", 80),
    ("inode", "i_sb", 0),
    ("super_block", "s_dev", 0),
];

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("vmlinux_offsets.rs");
    let btf_path = env::var("DFIM_BTF_PATH").unwrap_or_else(|_| DEFAULT_BTF_PATH.to_string());

    let offsets = parse_btf(Path::new(&btf_path)).unwrap_or_else(|err| {
        assert!(
            env::var_os("DFIM_ALLOW_UNVERIFIED_BTF_FALLBACK").is_some(),
            "DFIM requires target-kernel BTF ({btf_path}): {err}; \
             set DFIM_BTF_PATH or explicitly opt into compile-only fallback"
        );
        println!(
            "cargo:warning=UNSAFE FOR RUNTIME: BTF extraction failed ({err}); \
             using compile-only placeholder offsets"
        );
        UNVERIFIED_DEVELOPMENT_FALLBACK
            .iter()
            .map(|(s, f, o)| ((*s).to_string(), (*f).to_string(), *o))
            .collect()
    });

    for (struct_name, field, offset) in &offsets {
        println!("cargo:warning=CO-RE offset {struct_name}.{field} = {offset}");
    }

    let mut body = String::from("// @generated by build.rs — do not edit\n\n");
    for (struct_name, field, offset) in offsets {
        body.push_str(&format!(
            "pub const {}_{}: usize = {offset};\n",
            struct_name.to_uppercase(),
            field.to_uppercase()
        ));
    }

    fs::write(&out_path, body).expect("write vmlinux_offsets.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=DFIM_BTF_PATH");
    println!("cargo:rerun-if-env-changed=DFIM_ALLOW_UNVERIFIED_BTF_FALLBACK");
    if Path::new(&btf_path).exists() {
        println!("cargo:rerun-if-changed={btf_path}");
    }

    // sha2 compress256 exceeds the default 512 B BPF stack; raise frame limit for crypto paths.
    if env::var("TARGET")
        .map(|t| t.contains("bpf"))
        .unwrap_or(false)
    {
        println!("cargo:rustc-env=RUSTFLAGS=-Cllvm-args=-bpf-stack-size=16384");
    }
}

fn parse_btf(path: &Path) -> Result<Vec<(String, String, u32)>, String> {
    let data = fs::read(path).map_err(|e| format!("read BTF: {e}"))?;
    if data.len() < 24 {
        return Err("BTF too small".into());
    }

    let magic = u16::from_le_bytes([data[0], data[1]]);
    if magic != BTF_MAGIC {
        return Err(format!("bad BTF magic: {magic:#x}"));
    }

    let hdr_len = u32::from_le_bytes(data[4..8].try_into().unwrap()) as usize;
    let type_off = u32::from_le_bytes(data[8..12].try_into().unwrap()) as usize;
    let type_len = u32::from_le_bytes(data[12..16].try_into().unwrap()) as usize;
    let str_off = u32::from_le_bytes(data[16..20].try_into().unwrap()) as usize;
    let str_base = hdr_len + str_off;
    let type_base = hdr_len + type_off;

    let mut found = HashMap::new();
    let mut off = 0usize;

    while off < type_len {
        let (step, struct_name, members) = parse_type(&data, type_base + off, str_base)?;
        if let Some(struct_name) = struct_name {
            for (target_struct, target_field) in TARGETS {
                if struct_name == target_struct {
                    for (member, byte_offset) in &members {
                        if member == target_field {
                            found.insert((target_struct, target_field), *byte_offset);
                        }
                    }
                }
            }
        }
        off += step;
        if found.len() == TARGETS.len() {
            break;
        }
    }

    if found.len() != TARGETS.len() {
        return Err(format!(
            "incomplete offsets ({}/{}); last off={off}",
            found.len(),
            TARGETS.len()
        ));
    }

    let mut out = Vec::new();
    for (struct_name, field) in TARGETS {
        let offset = found
            .get(&(struct_name, field))
            .copied()
            .ok_or_else(|| format!("missing offset for {struct_name}.{field}"))?;
        out.push((struct_name.to_string(), field.to_string(), offset));
    }

    Ok(out)
}

fn parse_type(
    data: &[u8],
    base: usize,
    str_base: usize,
) -> Result<(usize, Option<String>, Vec<(String, u32)>), String> {
    if base + 8 > data.len() {
        return Err("truncated BTF type header".into());
    }
    let name_off = read_u32(&data[base..]);
    let info = read_u32(&data[base + 4..]);
    let kind = (info >> 24) & 0x1f;
    let vlen = (info & 0xFFFF) as usize;
    let name = read_cstr(data, str_base, name_off)?;

    match kind {
        4 | 5 => {
            if base + 12 + vlen * 12 > data.len() {
                return Err("truncated struct members".into());
            }
            let mut members = Vec::new();
            for i in 0..vlen {
                let pos = base + 12 + i * 12;
                let mname_off = read_u32(&data[pos..]);
                let moff = read_u32(&data[pos + 8..]);
                members.push((read_cstr(data, str_base, mname_off)?, (moff & 0xFFFFFF) / 8));
            }
            Ok((12 + vlen * 12, Some(name), members))
        }
        1 | 16 => Ok((16, None, Vec::new())),
        3 => Ok((24, None, Vec::new())),
        6 => Ok((12 + vlen * 8, None, Vec::new())),
        19 => Ok((12 + vlen * 12, None, Vec::new())),
        12 => Ok((12, None, Vec::new())),
        13 => Ok((12 + vlen * 8, None, Vec::new())),
        14 | 17 => Ok((16, None, Vec::new())),
        15 => Ok((12 + vlen * 16, None, Vec::new())),
        _ => Ok((12, None, Vec::new())),
    }
}

fn read_u32(bytes: &[u8]) -> u32 {
    u32::from_le_bytes(bytes[..4].try_into().expect("u32"))
}

fn read_cstr(data: &[u8], str_base: usize, off: u32) -> Result<String, String> {
    if off == 0 {
        return Ok(String::new());
    }
    let start = str_base + off as usize;
    if start >= data.len() {
        return Err(format!("string offset out of range: {off}"));
    }
    let end = data[start..]
        .iter()
        .position(|&b| b == 0)
        .map(|p| start + p)
        .ok_or_else(|| format!("unterminated string at {start}"))?;
    String::from_utf8(data[start..end].to_vec()).map_err(|e| e.to_string())
}
